// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SplitDemo {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DetailViewController")]
	public partial class DetailViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UINavigationBar __mt_navBar;
		
		private MonoTouch.UIKit.UILabel __mt_detailLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("navBar")]
		private MonoTouch.UIKit.UINavigationBar navBar {
			get {
				this.__mt_navBar = ((MonoTouch.UIKit.UINavigationBar)(this.GetNativeField("navBar")));
				return this.__mt_navBar;
			}
			set {
				this.__mt_navBar = value;
				this.SetNativeField("navBar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("detailLabel")]
		private MonoTouch.UIKit.UILabel detailLabel {
			get {
				this.__mt_detailLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("detailLabel")));
				return this.__mt_detailLabel;
			}
			set {
				this.__mt_detailLabel = value;
				this.SetNativeField("detailLabel", value);
			}
		}
	}
}
